name: Update Repo Variable
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Print variable
        run: echo ${{ vars.VERSION }}
        
      - name: Increment variable
        run: |
          IFS="." read -a version_array <<< ${{ vars.VERSION }}
          echo ${version_array}
          (( ++version_array[2] ))
          next_version="${version_array[0]}.${version_array[1]}.${version_array[2]}"
          echo ${next_version}
          echo "NEXT_VERSION=${next_version}" >> $GITHUB_ENV
        
      - name: Update variable
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/LukeLonas/action-update-repo-var/actions/variables/VERSION \
            -d '{"name":"VERSION","value":"${{ env.NEXT_VERSION }}"}'
